[COMMONC_PARAM_FIXUP_DIALOG]
FIXUP_PARAM_DLG_TITLE = "$Specify Parameter as Array or Pointer"
POINTER_BUTTON = "$Pointer"
ARRAY_BUTTON = "$Array"
EXPLANATION_TEXT Line1 = "$The type information for this parameter indicates that it is a pointer type. "
EXPLANATION_TEXT Line2 = "TestStand can pass the argument as a pointer to a single object or as an "
EXPLANATION_TEXT Line3 = "array of multiple objects. Press the Array or Pointer button below to "
EXPLANATION_TEXT Line4 = "indicate how you want TestStand to pass this parameter. If you choose Array, "
EXPLANATION_TEXT Line5 = "TestStand will provide a default array size for you that you should change to "
EXPLANATION_TEXT Line6 = "match your source code."

[STEP_MODULE_COMMONC_SETTINGS]
;; Controls
MODULE_PATH_NAME = "$Module Pathname:"
FUNCTION_CALL = "$Function Call:"
FUNCTION_NAME = "$Function:"

;; Tooltips
BROWSE_BUTTON_TOOLTIP = "$Browse..."
RELOAD_PROTOTYPE_TOOLTIP = "$Reload Prototype"
FUNCTION_HELP_TOOLTIP = "$Display Function Help"
ADD_PARAM_TOOLTIP = "$Add Parameter"
REMOVE_PARAM_TOOLTIP = "$Remove Selected Parameter"
MOVE_UP_TOOLTIP = "$Move Up Selected Parameter"
MOVE_DOWN_TOOLTIP = "$Move Down Selected Parameter"
PARAM_ERROR_BUTTON_TOOLTIP = "$%1 Go to error."
PARAM_UNKNOWN_INFO_BUTTON_TOOLTIP = "$Specify parameter as array or pointer..."
SOURCE_CODE_TOOLTIP = "$Source Code..."

;; Commands
CHANGE_MODULE_PATH = "$Module Pathname"
CHANGE_FUNCTION = "$Function Name"
CHANGE_TYPE = "$Parameter Type"
CHANGE_EXPR_VAL = "$Parameter Value Expression"
CHANGE_STRUCT_TYPE = "$Parameter Struct Type"
CHANGE_NAME = "$Parameter Name"
CHANGE_CATEGORY = "$Parameter Category"
CHANGE_PASS = "$Parameter Pass"
CHANGE_STRING_BUFFER_SIZE = "$Parameter String Buffer Size"
CHANGE_ARRAY_DIMENSIONS = "$Parameter Array Dimensions"
CHANGE_RESULT_ACTION = "$Parameter Result Action"
CHANGE_SET_ERROR_CODE = "$Parameter Set Error.Code"
CHANGE_ARRAY_DIM_SIZE = "$Parameter Array Size"
CHANGE_TSOBJECT_TYPE = "$Parameter TSObject Type"
CHANGE_PASS_SEQ_CONTEXT = "$Parameter Pass Sequence Context"
RELOAD_PROTOTYPE_COMMAND = "$Reload Function Prototype"
ADD_PARAM_COMMAND = "$Add Parameter"
REMOVE_PARAM_COMMAND = "$Remove Parameter"
MOVE_UP_COMMAND = "$Move Parameter Up"
MOVE_DOWN_COMMAND = "$Move Parameter Down"
FIXUP_UNKNOWN_INFO_COMMAND = "$Specify Parameter Type as Array or Pointer"

DEFAULT_ARG_NAME = "$arg%1"

;; Column titles
NAME_COLUMN = "$Name"
DESC_COLUMN = "$Description"
VAL_EXPR_COLUMN = "$Value Expression"

;; Row labels
NAME_ROW = "$Name"
CATEGORY_ROW = "$Category"
TYPE_ROW = "$Type"
PASS_ROW = "$Pass"
SET_ERROR_CODE_ROW = "$Set Error.Code"
RESULT_ACTION_ROW = "$Result Action"
ARRAY_DIMENSIONS_ROW = "$Dimensions"
ARRAY_DIM_ROW = "$Dim %1 Size"
STRING_BUFFER_SIZE_ROW = "$Buffer Size"
ELEM_PASS_ROW = "$Element Pass"
PASS_SEQ_CONTEXT_ROW = "$Pass Sequence Context"
;; Error messages
ERROR_STRING_BUFFER_SIZE_EXPR = "$Error in string buffer size expression."
ERROR_STRUCT_TYPE = "$Error in struct type."
ERROR_ARRAY_DIM_SIZE_EXPR = "$Error in array dimension size expression."

;; Enums
CommonCParameterTypes.CParamType_CString = "$C String (const)"
CommonCParameterTypes.CParamType_UnicodeString = "$Unicode String (const)"
CommonCParameterTypes.CParamType_CStringBuffer = "$C String Buffer" 
CommonCParameterTypes.CParamType_UnicodeStringBuffer = "$Unicode String Buffer"
CommonCParameterTypes.CParamType_Int8 = "$Signed 8-bit Integer"
CommonCParameterTypes.CParamType_UInt8 = "$Unsigned 8-bit Integer"
CommonCParameterTypes.CParamType_Int16 = "$Signed 16-bit Integer"
CommonCParameterTypes.CParamType_UInt16 = "$Unsigned 16-bit Integer"
CommonCParameterTypes.CParamType_Int32 = "$Signed 32-bit Integer"
CommonCParameterTypes.CParamType_UInt32 = "$Unsigned 32-bit Integer"
CommonCParameterTypes.CParamType_Float32 = "$32-bit Real Number (float)"
CommonCParameterTypes.CParamType_Float64 = "$64-bit Real Number (double)"
CommonCParameterTypes.CParamType_IDispatch = "$Active X Automation IDispatch Pointer"
CommonCParameterTypes.CParamType_CVIHandle = "$CVI Active X Automation Handle"
CommonCParameterTypes.CParamType_IUnknown = "$Active X Automation IUnknown Pointer"

CommonCParameterPassOptions.CParamPass_ByVal = "$By Value"
CommonCParameterPassOptions.CParamPass_ByConstPointer = "$By Const Pointer (const *)"
CommonCParameterPassOptions.CParamPass_ByConstReference = "$By Const Reference (const &)"
CommonCParameterPassOptions.CParamPass_ByPointer = "$By Pointer (*)"
CommonCParameterPassOptions.CParamPass_ByReference = "$By Reference (&)"

CommonCParameterArrayElemPassOptions.CParamPass_ByVal = "$Embedded Element"
CommonCParameterArrayElemPassOptions.CParamPass_ByPointer = "$Pointer to Element"

CommonCParameterResultActions.CParamResult_NoAction = "$No Action"
CommonCParameterResultActions.CParamResult_SetErrorIfNegative = "$If Value < 0 Set Error.Occurred to true"
CommonCParameterResultActions.CParamResult_SetErrorIfNotZero = "$If Value != 0 Set Error.Occurred to true"
CommonCParameterResultActions.CParamResult_SetErrorIfPositive = "$If Value > 0 Set Error.Occurred to true"
CommonCParameterResultActions.CParamResult_SetErrorIfZero = "$If Value == 0 Set Error.Occurred to true"

INCOMPATIBLE_PARAM_MESSAGE = "$Some parameters are incompatible with the specified function.\nPress the reload prototype button to resolve."

[STEP_MODULE_DLL_SETTINGS]
;; Enums
DllParameterCategories.DllParamCategory_Void = "$Void"
DllParameterCategories.DllParamCategory_Numeric = "$Numeric"
DllParameterCategories.DllParamCategory_Boolean = "$Boolean"
DllParameterCategories.DllParamCategory_String = "$String"
DllParameterCategories.DllParamCategory_Object = "$Object"
DllParameterCategories.DllParamCategory_TSObject = "$TS Object"
DllParameterCategories.DllParamCategory_CStruct = "$C Struct"
DllParameterCategories.DllParamCategory_NumericArray = "$Array of Numbers"
DllParameterCategories.DllParamCategory_BooleanArray = "$Array of Booleans"
DllParameterCategories.DllParamCategory_StringArray = "$Array of Strings"
DllParameterCategories.DllParamCategory_ObjectArray = "$Array of Objects"
DllParameterCategories.DllParamCategory_CStructArray = "$Array of C Structs"
DllParameterCategories.DllParamCategory_CNiVector = "$CNiVector"
DllParameterCategories.DllParamCategory_CNiMatrix = "$CNiMatrix"
DllParameterCategories.DllParamCategory_CNiComplex = "$CNiComplex"
DllParameterCategories.DllParamCategory_CNiComplexVector = "$CNiComplexVector"
DllParameterCategories.DllParamCategory_CNiString = "$CNiString"
DllParameterCategories.DllParamCategory_CNiStringVector = "$CNiStringVector"
DllParameterCategories.DllParamCategory_CNiBoolVector = "$CNiBoolVector"
DllParameterCategories.DllParamCategory_CString = "$CString"
DllParameterCategories.DllParamCategory_CStringArray = "$CStringArray"
DllParameterCategories.DllParamCategory_bstr_t = "$_bstr_t"
